name: '🔤 codetypo'
on:
  pull_request:
  push:
    branches:
      - v1
  workflow_dispatch:

jobs:
  codetypo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: khulnasoft/codetypo-action@main
        with:
          files: |
            **
            .*/**
          incremental_files_only: false
